api: yes
webrtc: yes

paths:
  kvm:
    runOnInit: sh -c '/home/alex/kvm_engine_py/kvm_engine | ffmpeg -loglevel quiet -use_wallclock_as_timestamps 1 -f h264 -i pipe:0 -c:v copy -bf 0 -rtsp_transport tcp -pkt_size 1200 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH 2>/dev/null'
    runOnInitRestart: yes
    alwaysAvailable: true
    alwaysAvailableTracks:
      - codec: H264