#logLevel: debug
authInternalUsers:
  - user: admin
    pass: password
    permissions:
      - action: read
        path: kvm
      - action: publish
        path: kvm
webrtc: true
webrtcLocalUDPAddress: :30000
webrtcAdditionalHosts: ["79.143.43.173"]
paths:
  kvm:
    runOnDemand: /home/alex/kvm_engine_py/start_ffmpeg.sh
    runOnDemandCloseAfter: 10s
    runOnDemandRestart: true
    #alwaysAvailable: true
    #alwaysAvailableTracks:
    #  - codec: H264
