api: yes
webrtc: yes
webrtcICEServers2:
  - url: turn:YOUR_PUBLIC_IP:3478
    username: my_turn_user
    password: my_secure_password

paths:
  kvm:
    runOnInit: sh -c '/home/alex/kvm_engine_py/kvm_engine | ffmpeg -loglevel info -use_wallclock_as_timestamps 1 -f h264 -i pipe:0 -c:v copy -bf 0 -rtsp_transport tcp -pkt_size 1200 -f rtsp rtsp://localhost:8554/kvm'
    runOnInitRestart: yes
    alwaysAvailable: true
    alwaysAvailableTracks:
      - codec: H264